1
// Должен загружаться первым, иначе другие объекты могут неправильно инициализироваться.
yield return _content.BattleBankContent;

// Усиление.

2
// Сервис упал. Не делать ничего.
                

// Прояснение в одной из ветки условий.

3
// TODO Поворот задан рукаму. Нужно вычислять. Детали в тикете 20507
private Quaternion _spine1pistol = new Quaternion(-0.617654324f, 0.6405527f, -0.314859748f, 0.330240339f);

// Комментарии TODO

4
// Текущий + предыдущий тик для интерполяции
const int hitBoxesDataCollectionSize = 2; 

// Прояснение

5
case DeviceId.Touch:
    // TODO Не реализовано

// Комментарии TODO


6 
// Ждем завершения запроса и добавление в другом потоке.
await loadInfoAwaiter;

// Представление намерений


7
// Сцены может еще не существовать.

// Усиление.

8
// Строка состоит из пробелов
Regex.IsMatch(s, @"^[\s]*$") 

// Информативные комментарии

9
/// <auto-generated>This is autogenerated class from <see cref="LocationContextFile"/></auto-generated>

// Информативные комментарии

10
// TODO: replace these replaces with Regex

//Комментарии TODO

11
//for tests only
public IEntitiesModel EntitiesModel { get; set; } 

// Предупреждения о последствиях

12
// Обязательно изучите содержимое соседних классов при внесении изменений.

// Предупреждения о последствиях

